
# User facing name that identifies the service.
name: Prefab

# How the server should be addressed externally when constructing URLs. In
# development, this is likely the hostname and port configured during server
# instantiation. In production, it may be a CDN or Load Balancer.
address: http://localhost:8000

# Server configuration.
server:
  # Host and port to bind to.
  host: localhost
  port: 8000

  # Key used to sign CSRF tokens. Changing this will invalidate any outstanding
  # tokens.
  csrfsigningkey: helloworld

  # Override the default GRPC max msg size.
  # maxmsgsizebytes: 10485760 # 10MB

  # If configured, the server will listen on TLS.
  # tls:
  #   certfile: './certs/cert.pem'
  #   keyfile: './certs/key.pem'

  # Whether to allow cross-origin requests.
  # corsorigins:
  #  - https://www.somesite.com
  #  - https://extension.thirdparty.com

  # Incoming headers that should be forwarded on to GRPC services.
  incomingheaders:
  - X-Requested-With

# Template rendering configuration.
templates:
  # Whether to reparse templates everytime they are executed. Should be false in
  # prod, but true makes dev easier.
  alwaysparse: true

  # List of directories to load templates from. Templates can be customized or 
  # overridden, they should be shipped with the binary.
  dirs:
  - ./templates/default

# Email sending configuration.
email:
  from: me@example.com
  smtp:
    host: email-smtp.us-east-1.amazonaws.com
    port: 465
    username: xxxxxxxxxx
    password: xxxxxxxxxx

# Authentication configuration.
auth:
  # Signing key for identity tokens.
  signingkey: helloworld
  # How long identity tokens should be valid for.
  expiration: 30d

  # Configuration for the magiclink plugin which allows for passwordless auth.
  magiclink:
    # JWT signing key for magic links. Changing this will invalidate any
    # outstanding links.
    signingkey: helloworld
    # How magiclinks should should be active for.
    expiration: 15m

  # Configuration for the google plugin, see:
  # https://console.cloud.google.com/apis/credentials/oauthclient
  google:
    id: xxxx.apps.googleusercontent.com
    secret: xxxxxxxxxx
