
# How the server should be addressed externally when constructing URLs. In
# development, this is likely the hostname and port configured during server
# instantiation. In production, it may be a CDN or Load Balancer.
address: http://localhost:8000

# Email sending configuration.
email:
  from: me@example.com
  smtp:
    host: email-smtp.us-east-1.amazonaws.com
    port: 465
    username: xxxxxxxxxx
    password: xxxxxxxxxx

# Authentication configuration.
auth:

  # Configuration for the magiclink plugin which allows for passwordless auth.
  magiclink:
    # JWT signing key. Changing this will invalidate any outstanding tokens.
    signingkey: helloworld
    # How magiclinks should should be active for.
    expiration: 1h
