// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: metaservice.proto

package prefab

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty request object.
type ClientConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientConfigRequest) Reset() {
	*x = ClientConfigRequest{}
	mi := &file_metaservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfigRequest) ProtoMessage() {}

func (x *ClientConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metaservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfigRequest.ProtoReflect.Descriptor instead.
func (*ClientConfigRequest) Descriptor() ([]byte, []int) {
	return file_metaservice_proto_rawDescGZIP(), []int{0}
}

// Configuration information to help clients facilitate interactions with the
// API server.
type ClientConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A map of key-value pairs configured by available plugins, for example
	// auth.google.client_id.
	Configs map[string]string `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Token that should be used in non-XHR requests to avoid cross-site request
	// forgery attacks.
	CsrfToken     string `protobuf:"bytes,2,opt,name=csrf_token,json=csrfToken,proto3" json:"csrf_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientConfigResponse) Reset() {
	*x = ClientConfigResponse{}
	mi := &file_metaservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfigResponse) ProtoMessage() {}

func (x *ClientConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metaservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfigResponse.ProtoReflect.Descriptor instead.
func (*ClientConfigResponse) Descriptor() ([]byte, []int) {
	return file_metaservice_proto_rawDescGZIP(), []int{1}
}

func (x *ClientConfigResponse) GetConfigs() map[string]string {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *ClientConfigResponse) GetCsrfToken() string {
	if x != nil {
		return x.CsrfToken
	}
	return ""
}

var File_metaservice_proto protoreflect.FileDescriptor

const file_metaservice_proto_rawDesc = "" +
	"\n" +
	"\x11metaservice.proto\x12\x06prefab\x1a\x1cgoogle/api/annotations.proto\x1a\fserver.proto\"\x15\n" +
	"\x13ClientConfigRequest\"\xb6\x01\n" +
	"\x14ClientConfigResponse\x12C\n" +
	"\aconfigs\x18\x01 \x03(\v2).prefab.ClientConfigResponse.ConfigsEntryR\aconfigs\x12\x1d\n" +
	"\n" +
	"csrf_token\x18\x02 \x01(\tR\tcsrfToken\x1a:\n" +
	"\fConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012y\n" +
	"\vMetaService\x12j\n" +
	"\fClientConfig\x12\x1b.prefab.ClientConfigRequest\x1a\x1c.prefab.ClientConfigResponse\"\x1f\x8a\xb5\x18\x03off\x82\xd3\xe4\x93\x02\x12\x12\x10/api/meta/configB\x18Z\x16github.com/dpup/prefabb\x06proto3"

var (
	file_metaservice_proto_rawDescOnce sync.Once
	file_metaservice_proto_rawDescData []byte
)

func file_metaservice_proto_rawDescGZIP() []byte {
	file_metaservice_proto_rawDescOnce.Do(func() {
		file_metaservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metaservice_proto_rawDesc), len(file_metaservice_proto_rawDesc)))
	})
	return file_metaservice_proto_rawDescData
}

var file_metaservice_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_metaservice_proto_goTypes = []any{
	(*ClientConfigRequest)(nil),  // 0: prefab.ClientConfigRequest
	(*ClientConfigResponse)(nil), // 1: prefab.ClientConfigResponse
	nil,                          // 2: prefab.ClientConfigResponse.ConfigsEntry
}
var file_metaservice_proto_depIdxs = []int32{
	2, // 0: prefab.ClientConfigResponse.configs:type_name -> prefab.ClientConfigResponse.ConfigsEntry
	0, // 1: prefab.MetaService.ClientConfig:input_type -> prefab.ClientConfigRequest
	1, // 2: prefab.MetaService.ClientConfig:output_type -> prefab.ClientConfigResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_metaservice_proto_init() }
func file_metaservice_proto_init() {
	if File_metaservice_proto != nil {
		return
	}
	file_server_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metaservice_proto_rawDesc), len(file_metaservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metaservice_proto_goTypes,
		DependencyIndexes: file_metaservice_proto_depIdxs,
		MessageInfos:      file_metaservice_proto_msgTypes,
	}.Build()
	File_metaservice_proto = out.File
	file_metaservice_proto_goTypes = nil
	file_metaservice_proto_depIdxs = nil
}
