// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: plugins/authz/authz.proto

package authz

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_plugins_authz_authz_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50011,
		Name:          "prefab.authz.action",
		Tag:           "bytes,50011,opt,name=action",
		Filename:      "plugins/authz/authz.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50012,
		Name:          "prefab.authz.resource",
		Tag:           "bytes,50012,opt,name=resource",
		Filename:      "plugins/authz/authz.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50013,
		Name:          "prefab.authz.default_effect",
		Tag:           "bytes,50013,opt,name=default_effect",
		Filename:      "plugins/authz/authz.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50021,
		Name:          "prefab.authz.id",
		Tag:           "varint,50021,opt,name=id",
		Filename:      "plugins/authz/authz.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50022,
		Name:          "prefab.authz.domain",
		Tag:           "varint,50022,opt,name=domain",
		Filename:      "plugins/authz/authz.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50023,
		Name:          "prefab.authz.scope",
		Tag:           "varint,50023,opt,name=scope",
		Filename:      "plugins/authz/authz.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional string action = 50011;
	E_Action = &file_plugins_authz_authz_proto_extTypes[0]
	// optional string resource = 50012;
	E_Resource = &file_plugins_authz_authz_proto_extTypes[1]
	// optional string default_effect = 50013;
	E_DefaultEffect = &file_plugins_authz_authz_proto_extTypes[2]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool id = 50021;
	E_Id = &file_plugins_authz_authz_proto_extTypes[3]
	// optional bool domain = 50022;
	E_Domain = &file_plugins_authz_authz_proto_extTypes[4] // Deprecated: use scope instead
	// optional bool scope = 50023;
	E_Scope = &file_plugins_authz_authz_proto_extTypes[5]
)

var File_plugins_authz_authz_proto protoreflect.FileDescriptor

const file_plugins_authz_authz_proto_rawDesc = "" +
	"\n" +
	"\x19plugins/authz/authz.proto\x12\fprefab.authz\x1a google/protobuf/descriptor.proto:8\n" +
	"\x06action\x12\x1e.google.protobuf.MethodOptions\x18ۆ\x03 \x01(\tR\x06action:<\n" +
	"\bresource\x12\x1e.google.protobuf.MethodOptions\x18܆\x03 \x01(\tR\bresource:G\n" +
	"\x0edefault_effect\x12\x1e.google.protobuf.MethodOptions\x18݆\x03 \x01(\tR\rdefaultEffect:/\n" +
	"\x02id\x12\x1d.google.protobuf.FieldOptions\x18\xe5\x86\x03 \x01(\bR\x02id:7\n" +
	"\x06domain\x12\x1d.google.protobuf.FieldOptions\x18\xe6\x86\x03 \x01(\bR\x06domain:5\n" +
	"\x05scope\x12\x1d.google.protobuf.FieldOptions\x18\xe7\x86\x03 \x01(\bR\x05scopeB&Z$github.com/dpup/prefab/plugins/authzb\x06proto3"

var file_plugins_authz_authz_proto_goTypes = []any{
	(*descriptorpb.MethodOptions)(nil), // 0: google.protobuf.MethodOptions
	(*descriptorpb.FieldOptions)(nil),  // 1: google.protobuf.FieldOptions
}
var file_plugins_authz_authz_proto_depIdxs = []int32{
	0, // 0: prefab.authz.action:extendee -> google.protobuf.MethodOptions
	0, // 1: prefab.authz.resource:extendee -> google.protobuf.MethodOptions
	0, // 2: prefab.authz.default_effect:extendee -> google.protobuf.MethodOptions
	1, // 3: prefab.authz.id:extendee -> google.protobuf.FieldOptions
	1, // 4: prefab.authz.domain:extendee -> google.protobuf.FieldOptions
	1, // 5: prefab.authz.scope:extendee -> google.protobuf.FieldOptions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	0, // [0:6] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_plugins_authz_authz_proto_init() }
func file_plugins_authz_authz_proto_init() {
	if File_plugins_authz_authz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugins_authz_authz_proto_rawDesc), len(file_plugins_authz_authz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 6,
			NumServices:   0,
		},
		GoTypes:           file_plugins_authz_authz_proto_goTypes,
		DependencyIndexes: file_plugins_authz_authz_proto_depIdxs,
		ExtensionInfos:    file_plugins_authz_authz_proto_extTypes,
	}.Build()
	File_plugins_authz_authz_proto = out.File
	file_plugins_authz_authz_proto_goTypes = nil
	file_plugins_authz_authz_proto_depIdxs = nil
}
