// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: plugins/auth/authservice.proto

package auth

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A client request to authenticate the user. For instance:
//
//	{ "provider": "magiclink", "creds": {"email": "walt@disney.com"} }
type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the auth-provider to use to process the creds.
	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// Creds contains key/value pairs of provider specific credentials.
	Creds map[string]string `protobuf:"bytes,2,rep,name=creds,proto3" json:"creds,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Whether a token should be returned in the response. If false, a cookie will
	// be set on the API root.
	IssueToken bool `protobuf:"varint,3,opt,name=issue_token,json=issueToken,proto3" json:"issue_token,omitempty"`
	// The URL where the user should be redirected after the cookie is set.
	// Incompatible with `issue_token`.
	RedirectUri   string `protobuf:"bytes,4,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_plugins_auth_authservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_auth_authservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_plugins_auth_authservice_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LoginRequest) GetCreds() map[string]string {
	if x != nil {
		return x.Creds
	}
	return nil
}

func (x *LoginRequest) GetIssueToken() bool {
	if x != nil {
		return x.IssueToken
	}
	return false
}

func (x *LoginRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

// The login response.
type LoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the token was issued. False does not necessarily indicate an error,
	// some auth providers may require an additional step. For example, magiclink
	// requires the user follow a URL that was sent to their email.
	Issued bool `protobuf:"varint,1,opt,name=issued,proto3" json:"issued,omitempty"`
	// An auth token which can be used to make subsequently authenticated requests
	// only set if `issue_token` is true.
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// Destination where the client should be redirected to, if applicable. HTTP
	// headers will be added to GRPC metadata which will cause a 302 redirect if
	// the RPC is called via the GRPC Gateway. Not compatible with `issue_token`
	// set to true.
	RedirectUri   string `protobuf:"bytes,3,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_plugins_auth_authservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_auth_authservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_plugins_auth_authservice_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetIssued() bool {
	if x != nil {
		return x.Issued
	}
	return false
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

// The login response.
type LogoutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The URL where the user should be redirected after a successful logout.
	RedirectUri   string `protobuf:"bytes,4,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_plugins_auth_authservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_auth_authservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_plugins_auth_authservice_proto_rawDescGZIP(), []int{2}
}

func (x *LogoutRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

// The logout response.
type LogoutResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Destination where the client should be redirected to, if applicable. HTTP
	// headers will be added to GRPC metadata which will cause a 302 redirect if
	// the RPC is called via the GRPC Gateway.
	RedirectUri   string `protobuf:"bytes,1,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_plugins_auth_authservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_auth_authservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_plugins_auth_authservice_proto_rawDescGZIP(), []int{3}
}

func (x *LogoutResponse) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

// Empty request object.
type ConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigRequest) Reset() {
	*x = ConfigRequest{}
	mi := &file_plugins_auth_authservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRequest) ProtoMessage() {}

func (x *ConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_auth_authservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRequest.ProtoReflect.Descriptor instead.
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return file_plugins_auth_authservice_proto_rawDescGZIP(), []int{4}
}

// Configuration information to help clients facilitate login.
type ConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token that should be used in non-XHR requests to avoid cross-site request
	// forgery attacks.
	CsrfToken string `protobuf:"bytes,1,opt,name=csrf_token,json=csrfToken,proto3" json:"csrf_token,omitempty"`
	// A map of key-value pairs configured by available auth plugins, for example
	// google.client_id.
	Configs       map[string]string `protobuf:"bytes,2,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_plugins_auth_authservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_auth_authservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_plugins_auth_authservice_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigResponse) GetCsrfToken() string {
	if x != nil {
		return x.CsrfToken
	}
	return ""
}

func (x *ConfigResponse) GetConfigs() map[string]string {
	if x != nil {
		return x.Configs
	}
	return nil
}

// Empty request object. Auth credentials come from headers or cookie.
type IdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityRequest) Reset() {
	*x = IdentityRequest{}
	mi := &file_plugins_auth_authservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityRequest) ProtoMessage() {}

func (x *IdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_auth_authservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityRequest.ProtoReflect.Descriptor instead.
func (*IdentityRequest) Descriptor() ([]byte, []int) {
	return file_plugins_auth_authservice_proto_rawDescGZIP(), []int{6}
}

// Information about the authenticated identity.
type IdentityResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Provider string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// An auth provider specific identifier used to authenticate the user.
	Subject string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// An email address associated with the identity, if available.
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// Whether the email is thought to have been verified.
	EmailVerified bool `protobuf:"varint,4,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	// A name associated with the identity, if available.
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	// Delegation information if this identity was assumed by an admin.
	Delegation    *DelegationInfo `protobuf:"bytes,6,opt,name=delegation,proto3" json:"delegation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityResponse) Reset() {
	*x = IdentityResponse{}
	mi := &file_plugins_auth_authservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityResponse) ProtoMessage() {}

func (x *IdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_auth_authservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityResponse.ProtoReflect.Descriptor instead.
func (*IdentityResponse) Descriptor() ([]byte, []int) {
	return file_plugins_auth_authservice_proto_rawDescGZIP(), []int{7}
}

func (x *IdentityResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *IdentityResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *IdentityResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *IdentityResponse) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *IdentityResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IdentityResponse) GetDelegation() *DelegationInfo {
	if x != nil {
		return x.Delegation
	}
	return nil
}

// Metadata about identity delegation when an admin assumes another user's identity.
type DelegationInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Original admin's subject identifier (e.g., "google123")
	DelegatorSub string `protobuf:"bytes,1,opt,name=delegator_sub,json=delegatorSub,proto3" json:"delegator_sub,omitempty"`
	// Original admin's identity provider (e.g., "google")
	DelegatorProvider string `protobuf:"bytes,2,opt,name=delegator_provider,json=delegatorProvider,proto3" json:"delegator_provider,omitempty"`
	// Original admin's session ID (jti claim)
	DelegatorSessionId string `protobuf:"bytes,3,opt,name=delegator_session_id,json=delegatorSessionId,proto3" json:"delegator_session_id,omitempty"`
	// Reason provided for the delegation (e.g., "support-case-873")
	Reason string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	// Timestamp when the delegation occurred (Unix timestamp in seconds)
	DelegatedAt   int64 `protobuf:"varint,5,opt,name=delegated_at,json=delegatedAt,proto3" json:"delegated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelegationInfo) Reset() {
	*x = DelegationInfo{}
	mi := &file_plugins_auth_authservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegationInfo) ProtoMessage() {}

func (x *DelegationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_auth_authservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegationInfo.ProtoReflect.Descriptor instead.
func (*DelegationInfo) Descriptor() ([]byte, []int) {
	return file_plugins_auth_authservice_proto_rawDescGZIP(), []int{8}
}

func (x *DelegationInfo) GetDelegatorSub() string {
	if x != nil {
		return x.DelegatorSub
	}
	return ""
}

func (x *DelegationInfo) GetDelegatorProvider() string {
	if x != nil {
		return x.DelegatorProvider
	}
	return ""
}

func (x *DelegationInfo) GetDelegatorSessionId() string {
	if x != nil {
		return x.DelegatorSessionId
	}
	return ""
}

func (x *DelegationInfo) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DelegationInfo) GetDelegatedAt() int64 {
	if x != nil {
		return x.DelegatedAt
	}
	return 0
}

// Request to assume another user's identity.
type AssumeIdentityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target user's identity provider (e.g., "google")
	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// Target user's subject identifier
	Subject string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// Reason for assuming this identity (required for audit trail)
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssumeIdentityRequest) Reset() {
	*x = AssumeIdentityRequest{}
	mi := &file_plugins_auth_authservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssumeIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssumeIdentityRequest) ProtoMessage() {}

func (x *AssumeIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_auth_authservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssumeIdentityRequest.ProtoReflect.Descriptor instead.
func (*AssumeIdentityRequest) Descriptor() ([]byte, []int) {
	return file_plugins_auth_authservice_proto_rawDescGZIP(), []int{9}
}

func (x *AssumeIdentityRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AssumeIdentityRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AssumeIdentityRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Response containing the delegated identity token.
type AssumeIdentityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JWT token with the assumed identity and delegation metadata
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssumeIdentityResponse) Reset() {
	*x = AssumeIdentityResponse{}
	mi := &file_plugins_auth_authservice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssumeIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssumeIdentityResponse) ProtoMessage() {}

func (x *AssumeIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_auth_authservice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssumeIdentityResponse.ProtoReflect.Descriptor instead.
func (*AssumeIdentityResponse) Descriptor() ([]byte, []int) {
	return file_plugins_auth_authservice_proto_rawDescGZIP(), []int{10}
}

func (x *AssumeIdentityResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_plugins_auth_authservice_proto protoreflect.FileDescriptor

const file_plugins_auth_authservice_proto_rawDesc = "" +
	"\n" +
	"\x1eplugins/auth/authservice.proto\x12\vprefab.auth\x1a\x1cgoogle/api/annotations.proto\"\xe4\x01\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12:\n" +
	"\x05creds\x18\x02 \x03(\v2$.prefab.auth.LoginRequest.CredsEntryR\x05creds\x12\x1f\n" +
	"\vissue_token\x18\x03 \x01(\bR\n" +
	"issueToken\x12!\n" +
	"\fredirect_uri\x18\x04 \x01(\tR\vredirectUri\x1a8\n" +
	"\n" +
	"CredsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"`\n" +
	"\rLoginResponse\x12\x16\n" +
	"\x06issued\x18\x01 \x01(\bR\x06issued\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12!\n" +
	"\fredirect_uri\x18\x03 \x01(\tR\vredirectUri\"2\n" +
	"\rLogoutRequest\x12!\n" +
	"\fredirect_uri\x18\x04 \x01(\tR\vredirectUri\"3\n" +
	"\x0eLogoutResponse\x12!\n" +
	"\fredirect_uri\x18\x01 \x01(\tR\vredirectUri\"\x0f\n" +
	"\rConfigRequest\"\xaf\x01\n" +
	"\x0eConfigResponse\x12\x1d\n" +
	"\n" +
	"csrf_token\x18\x01 \x01(\tR\tcsrfToken\x12B\n" +
	"\aconfigs\x18\x02 \x03(\v2(.prefab.auth.ConfigResponse.ConfigsEntryR\aconfigs\x1a:\n" +
	"\fConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x11\n" +
	"\x0fIdentityRequest\"\xd6\x01\n" +
	"\x10IdentityResponse\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12%\n" +
	"\x0eemail_verified\x18\x04 \x01(\bR\remailVerified\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12;\n" +
	"\n" +
	"delegation\x18\x06 \x01(\v2\x1b.prefab.auth.DelegationInfoR\n" +
	"delegation\"\xd1\x01\n" +
	"\x0eDelegationInfo\x12#\n" +
	"\rdelegator_sub\x18\x01 \x01(\tR\fdelegatorSub\x12-\n" +
	"\x12delegator_provider\x18\x02 \x01(\tR\x11delegatorProvider\x120\n" +
	"\x14delegator_session_id\x18\x03 \x01(\tR\x12delegatorSessionId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12!\n" +
	"\fdelegated_at\x18\x05 \x01(\x03R\vdelegatedAt\"e\n" +
	"\x15AssumeIdentityRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\".\n" +
	"\x16AssumeIdentityResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\xc7\x03\n" +
	"\vAuthService\x12m\n" +
	"\x05Login\x12\x19.prefab.auth.LoginRequest\x1a\x1a.prefab.auth.LoginResponse\"-\x82\xd3\xe4\x93\x02'Z\x14:\x01*\"\x0f/api/auth/login\x12\x0f/api/auth/login\x12r\n" +
	"\x06Logout\x12\x1a.prefab.auth.LogoutRequest\x1a\x1b.prefab.auth.LogoutResponse\"/\x82\xd3\xe4\x93\x02)Z\x15:\x01*\"\x10/api/auth/logout\x12\x10/api/auth/logout\x12]\n" +
	"\bIdentity\x12\x1c.prefab.auth.IdentityRequest\x1a\x1d.prefab.auth.IdentityResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/auth/me\x12v\n" +
	"\x0eAssumeIdentity\x12\".prefab.auth.AssumeIdentityRequest\x1a#.prefab.auth.AssumeIdentityResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/auth/assumeB%Z#github.com/dpup/prefab/plugins/authb\x06proto3"

var (
	file_plugins_auth_authservice_proto_rawDescOnce sync.Once
	file_plugins_auth_authservice_proto_rawDescData []byte
)

func file_plugins_auth_authservice_proto_rawDescGZIP() []byte {
	file_plugins_auth_authservice_proto_rawDescOnce.Do(func() {
		file_plugins_auth_authservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugins_auth_authservice_proto_rawDesc), len(file_plugins_auth_authservice_proto_rawDesc)))
	})
	return file_plugins_auth_authservice_proto_rawDescData
}

var file_plugins_auth_authservice_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_plugins_auth_authservice_proto_goTypes = []any{
	(*LoginRequest)(nil),           // 0: prefab.auth.LoginRequest
	(*LoginResponse)(nil),          // 1: prefab.auth.LoginResponse
	(*LogoutRequest)(nil),          // 2: prefab.auth.LogoutRequest
	(*LogoutResponse)(nil),         // 3: prefab.auth.LogoutResponse
	(*ConfigRequest)(nil),          // 4: prefab.auth.ConfigRequest
	(*ConfigResponse)(nil),         // 5: prefab.auth.ConfigResponse
	(*IdentityRequest)(nil),        // 6: prefab.auth.IdentityRequest
	(*IdentityResponse)(nil),       // 7: prefab.auth.IdentityResponse
	(*DelegationInfo)(nil),         // 8: prefab.auth.DelegationInfo
	(*AssumeIdentityRequest)(nil),  // 9: prefab.auth.AssumeIdentityRequest
	(*AssumeIdentityResponse)(nil), // 10: prefab.auth.AssumeIdentityResponse
	nil,                            // 11: prefab.auth.LoginRequest.CredsEntry
	nil,                            // 12: prefab.auth.ConfigResponse.ConfigsEntry
}
var file_plugins_auth_authservice_proto_depIdxs = []int32{
	11, // 0: prefab.auth.LoginRequest.creds:type_name -> prefab.auth.LoginRequest.CredsEntry
	12, // 1: prefab.auth.ConfigResponse.configs:type_name -> prefab.auth.ConfigResponse.ConfigsEntry
	8,  // 2: prefab.auth.IdentityResponse.delegation:type_name -> prefab.auth.DelegationInfo
	0,  // 3: prefab.auth.AuthService.Login:input_type -> prefab.auth.LoginRequest
	2,  // 4: prefab.auth.AuthService.Logout:input_type -> prefab.auth.LogoutRequest
	6,  // 5: prefab.auth.AuthService.Identity:input_type -> prefab.auth.IdentityRequest
	9,  // 6: prefab.auth.AuthService.AssumeIdentity:input_type -> prefab.auth.AssumeIdentityRequest
	1,  // 7: prefab.auth.AuthService.Login:output_type -> prefab.auth.LoginResponse
	3,  // 8: prefab.auth.AuthService.Logout:output_type -> prefab.auth.LogoutResponse
	7,  // 9: prefab.auth.AuthService.Identity:output_type -> prefab.auth.IdentityResponse
	10, // 10: prefab.auth.AuthService.AssumeIdentity:output_type -> prefab.auth.AssumeIdentityResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_plugins_auth_authservice_proto_init() }
func file_plugins_auth_authservice_proto_init() {
	if File_plugins_auth_authservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugins_auth_authservice_proto_rawDesc), len(file_plugins_auth_authservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugins_auth_authservice_proto_goTypes,
		DependencyIndexes: file_plugins_auth_authservice_proto_depIdxs,
		MessageInfos:      file_plugins_auth_authservice_proto_msgTypes,
	}.Build()
	File_plugins_auth_authservice_proto = out.File
	file_plugins_auth_authservice_proto_goTypes = nil
	file_plugins_auth_authservice_proto_depIdxs = nil
}
