// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: examples/simpleserver/simpleservice/simpleservice.proto

package simpleservice

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An empty request with no parameters for now.
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_examples_simpleserver_simpleservice_simpleservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_simpleserver_simpleservice_simpleservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_examples_simpleserver_simpleservice_simpleservice_proto_rawDescGZIP(), []int{0}
}

// The response message containing the current health status.
type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How the server is feeling.
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_examples_simpleserver_simpleservice_simpleservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_simpleserver_simpleservice_simpleservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_examples_simpleserver_simpleservice_simpleservice_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ping          string                 `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_examples_simpleserver_simpleservice_simpleservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_simpleserver_simpleservice_simpleservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_examples_simpleserver_simpleservice_simpleservice_proto_rawDescGZIP(), []int{2}
}

func (x *EchoRequest) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pong          string                 `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_examples_simpleserver_simpleservice_simpleservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_simpleserver_simpleservice_simpleservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_examples_simpleserver_simpleservice_simpleservice_proto_rawDescGZIP(), []int{3}
}

func (x *EchoResponse) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

var File_examples_simpleserver_simpleservice_simpleservice_proto protoreflect.FileDescriptor

const file_examples_simpleserver_simpleservice_simpleservice_proto_rawDesc = "" +
	"\n" +
	"7examples/simpleserver/simpleservice/simpleservice.proto\x12\x06prefab\x1a\x1cgoogle/api/annotations.proto\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"!\n" +
	"\vEchoRequest\x12\x12\n" +
	"\x04ping\x18\x01 \x01(\tR\x04ping\"\"\n" +
	"\fEchoResponse\x12\x12\n" +
	"\x04pong\x18\x01 \x01(\tR\x04pong2\xa3\x01\n" +
	"\rSimpleService\x12L\n" +
	"\x06Health\x12\x15.prefab.HealthRequest\x1a\x16.prefab.HealthResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/api/health\x12D\n" +
	"\x04Echo\x12\x13.prefab.EchoRequest\x1a\x14.prefab.EchoResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/api/echoB<Z:github.com/dpup/prefab/examples/simpleserver/simpleserviceb\x06proto3"

var (
	file_examples_simpleserver_simpleservice_simpleservice_proto_rawDescOnce sync.Once
	file_examples_simpleserver_simpleservice_simpleservice_proto_rawDescData []byte
)

func file_examples_simpleserver_simpleservice_simpleservice_proto_rawDescGZIP() []byte {
	file_examples_simpleserver_simpleservice_simpleservice_proto_rawDescOnce.Do(func() {
		file_examples_simpleserver_simpleservice_simpleservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_simpleserver_simpleservice_simpleservice_proto_rawDesc), len(file_examples_simpleserver_simpleservice_simpleservice_proto_rawDesc)))
	})
	return file_examples_simpleserver_simpleservice_simpleservice_proto_rawDescData
}

var file_examples_simpleserver_simpleservice_simpleservice_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_examples_simpleserver_simpleservice_simpleservice_proto_goTypes = []any{
	(*HealthRequest)(nil),  // 0: prefab.HealthRequest
	(*HealthResponse)(nil), // 1: prefab.HealthResponse
	(*EchoRequest)(nil),    // 2: prefab.EchoRequest
	(*EchoResponse)(nil),   // 3: prefab.EchoResponse
}
var file_examples_simpleserver_simpleservice_simpleservice_proto_depIdxs = []int32{
	0, // 0: prefab.SimpleService.Health:input_type -> prefab.HealthRequest
	2, // 1: prefab.SimpleService.Echo:input_type -> prefab.EchoRequest
	1, // 2: prefab.SimpleService.Health:output_type -> prefab.HealthResponse
	3, // 3: prefab.SimpleService.Echo:output_type -> prefab.EchoResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_simpleserver_simpleservice_simpleservice_proto_init() }
func file_examples_simpleserver_simpleservice_simpleservice_proto_init() {
	if File_examples_simpleserver_simpleservice_simpleservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_simpleserver_simpleservice_simpleservice_proto_rawDesc), len(file_examples_simpleserver_simpleservice_simpleservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_simpleserver_simpleservice_simpleservice_proto_goTypes,
		DependencyIndexes: file_examples_simpleserver_simpleservice_simpleservice_proto_depIdxs,
		MessageInfos:      file_examples_simpleserver_simpleservice_simpleservice_proto_msgTypes,
	}.Build()
	File_examples_simpleserver_simpleservice_simpleservice_proto = out.File
	file_examples_simpleserver_simpleservice_simpleservice_proto_goTypes = nil
	file_examples_simpleserver_simpleservice_simpleservice_proto_depIdxs = nil
}
